---
title: "Life Expectancy Over Time"
output: html_document
---

```{r include=FALSE, message=FALSE}
library(tidyverse)
library(plotly)
library(RColorBrewer)
library(gganimate)
library(ggplot2)
library(viridis)


knitr::opts_chunk$set(
  echo = TRUE,
  fig.asp = .6,
  fig.width = 6,
  fig.height = 4,
  out.height = 400,
  dpi = 800,
  out.width = "80%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```


```{r include=FALSE, message=FALSE}
life_exp_df = 
  read_csv("data/Complete_Data.CSV") %>% 
  mutate(
    country = recode(country, "United Kingdom of Great Britain and Northern Ireland" = "United Kingdom")
  )
```

## Global Trend of Life Expectancy From 2000 to 2015

```{r message=FALSE}
world_life_exp =
  life_exp_df %>% 
  group_by(year) %>% 
  summarize(avg = mean(lifeexpectancy)) %>% 
  ggplot(aes(x = year, y = avg)) +
  geom_line(color = "#377EB8") +
  geom_point(alpha = .5, color = "#377EB8") +
  labs(
    x = "Year",
    y = "Life Expectancy",
    color = "Continent"
  ) +
  transition_reveal(as.integer(year))

animate(world_life_exp, duration = 8, renderer = gifski_renderer())

#ggplotly(world_life_exp)
```

## World Life Expectancy From 2000 to 2015 By Continent

```{r message=FALSE}
life_exp_continent =
  life_exp_df %>%
  group_by(continent,year) %>% 
  summarize(avg = mean(lifeexpectancy)) %>% 
  ggplot(aes(x = year, y = avg, color = continent)) +
  geom_line() +
  geom_point(alpha = 0.5) +
  labs(
    x = "Year",
    y = "Life Expectancy"
  ) +
  transition_reveal(as.integer(year))

animate(life_exp_continent, duration = 8, renderer = gifski_renderer())

#ggplotly(life_exp_continent)
```

## Top 10 Countries with the Highest Life Expectancy

```{r}
top_le_country =
  life_exp_df %>% 
  group_by(country) %>% 
  summarize(avg = mean(lifeexpectancy)) %>%
  arrange(desc(avg)) %>% 
  rename("Country" = "country", "Average Life Expectancy" =  "avg") %>% 
  head(10) %>% 
  knitr::kable(bootstrap_options = "striped", full_width = F, position = "left")

top_le_country
```


## Correlation Between the Development Status of A Country And Life Expectancy


```{r message=FALSE, warning=FALSE}
develop_plt = 
  life_exp_df %>% 
  ggplot(aes(x = status, y = lifeexpectancy, fill = status)) +
  geom_violin(width = 1) +
  geom_boxplot(width = 0.1, color = "red", alpha = 0.2) +
  scale_fill_hue(c = 45, l = 80) +
  theme(
      legend.position = "none",
      plot.title = element_text(size = 11)
    ) +
  stat_summary(
    fun = mean, aes(color = "Mean"), 
    geom = "point", 
    shape = 18, 
    size = 2.5,
    position = position_dodge(width = 0.75)) +
  scale_colour_manual(
    values = c("Mean" = "white")) +
  labs(
    x = "Development Status",
    y = "Life Expectancy"
  ) 

develop_plt

life_exp_df %>% 
  select(lifeexpectancy, status) %>% 
  group_by(status) %>%
  summarize(mean_expectancy = mean(lifeexpectancy)) %>% 
  knitr::kable(digits = 2)
```

## Map depicting average life expectancy in each country

```{r, warning=FALSE, message=FALSE}

ge = list(
showframe = TRUE,
showcoastlines = TRUE,
projection = list(type = 'Mercator')
)

life_exp_df %>% 
  group_by(country) %>% 
  summarize(mean_LE = mean(lifeexpectancy)) %>% 
  plot_geo(locationmode = "country names") %>%
    add_trace(locations = ~ country,
             z = ~mean_LE,
             color = ~mean_LE,
             colorscale = "Viridis") %>%
    layout(
      title = "Average Life Expectancy by Country",
      labels = "Mean Life Expectancy",
  geo = ge)

```

## Correlation Between GDP Values And Life Expectancy

```{r message=FALSE}
gdp_le =
  life_exp_df %>%
  mutate(
    continent = as.factor(continent),
    continent = fct_relevel(continent, c("Africa","Americas","Oceania","Asia", "Europe"))) %>% 
  ggplot(aes(x = lifeexpectancy, y = gdp, color = country)) +
  geom_point(alpha = .6) +
  labs(
    x = "Life Expectancy",
    y = "GDP Value"
  ) +
  facet_grid(.~ continent)  +
  guides(
    shape = guide_legend(override.aes = list(size = 3)),
    color = guide_legend(override.aes = list(size = 3)))  +
  theme(legend.title = element_text(size = 7), 
        legend.text  = element_text(size = 6),
        legend.key.size = unit(4, "cm"))

ggplotly(gdp_le)

```

