---
title: "Regression Analysis"
output: html_document
---
<br>

```{r include=FALSE, message=FALSE}
library(tidyverse)
library(modelr)
library(mgcv)
library(corrplot)
library(olsrr)
library(leaps)

knitr::opts_chunk$set(
  echo = TRUE,
  fig.width = 6,
  fig.asp = .7,
  dpi = 800,
  out.width = "70%"
)

theme_set(theme_minimal())

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```


```{r include=FALSE, message=FALSE}
le_df = 
  read_csv("./data/Dummy_Data.CSV")
```

<br>

## Correlation Matrix

```{r}
cm_df =
  le_df %>%
  dplyr::select(-c(country,continent))

corrplot(cor(cm_df), type = "upper", diag = FALSE, method = "square", addCoef.col = "black", number.cex = .3, tl.col = "black", tl.cex = .7)
```

<br>

<hr>

## Model building 

### Models Based on Prior Research

<br>
<br>

### Models Based on Automated Model Selection

**Stepwise Regression:**

<br>
<br>

**Forward Selection:**

<br>
<br>

**Backward Elimination:**

<br>
<br>

**Best Subsets Regression:**

<br>

*Best Fitting Models Based on the Numbers of Predictors*
```{r include=FALSE}
sub_fit = regsubsets(le ~ status_Developed + adult_mort + infantdeaths + alcohol + percent_exp + hepatitis_b_high + hepatitis_b_low + measles + bmi + under_five + polio_high + polio_low + total_exp + diphtheria_high + diphtheria_low + hiv_aids + gdp + population + thin_1_19 + thin_5_9 + HDI + schooling, data = le_df)

best_summary = summary(sub_fit)
best_summary_df = 
  as.data.frame(best_summary$outmat) %>% 
  remove_rownames() %>% 
  add_column(" " = c(1:8), .before = "year")

table = as.data.frame(t(best_summary_df[-1])) %>% 
  rename("1" = "V1", "2" = "V2", "3" = "V3","4" = "V4", "5" = "V5", "6" = "V6","7" = "V7", "8" = "V8")
```

```{r}
table %>% 
     knitr::kable()
```

<br>

*Comparison Based on Model Selection Criteria*
```{r}
Model_comparison =
  tibble(
	n_pred = c(1:8),
	"Adjusted R2" = best_summary$adjr2,
	"BIC" = best_summary$bic,
	"Cp" = best_summary$cp,
	"RSE" = best_summary$rsq,
	"RSS" = best_summary$rss
	) %>%
	gather(key = "Statistics", value = "value", 2:6) %>%
	ggplot(aes(x = n_pred, y = value)) +
	  geom_point() +
	  geom_line() +
	  facet_grid(Statistics ~ ., scales = "free_y") +
	  labs(
	  	x = "Number of Predictors",
	  	y = "Values",
	  	title = "Model Selection Criteria Comparison"
	  )

Model_comparison
```


<br>
<br>

<hr>

## Cross Validation

```{r include=FALSE}
#stepwise
mod_1 = lm(le ~ status_Developed + adult_mort + bmi + polio_high + diphtheria_low + hiv_aids + gdp + thin_1_19 + HDI + schooling, data = le_df)

#health
mod_2 = lm(le ~ polio_high + total_exp + diphtheria_low + hiv_aids + thin_1_19, data = le_df)

#full model
mod_3 = lm(le ~ status_Developed + adult_mort + infantdeaths + bmi + polio_high + diphtheria_low + hiv_aids + gdp + HDI + schooling, data = le_df)

# model_7
mod_4 = lm(le ~ status_Developed + percent_exp + HDI + adult_mort + infantdeaths + schooling, data = le_df)

#backward
mod_5 = lm(le ~ status_Developed + adult_mort + bmi + polio_high + diphtheria_low + hiv_aids + gdp + thin_1_19 + HDI + schooling, data = le_df)

#forward
mod_6 = lm(le ~ status_Developed + adult_mort + infantdeaths + bmi + polio_high + diphtheria_low + hiv_aids + gdp + HDI + schooling, data = le_df)

#best subsets selection 
mod_7 = lm(le ~ adult_mort + infantdeaths + polio_high + hiv_aids + gdp + HDI + schooling, data = le_df)

```

```{r include=FALSE}
set.seed(2)

cv_df = 
  crossv_mc(le_df,100) %>% 
  mutate(
    train = map(train, as_tibble),
    test = map(test, as_tibble)
  ) %>% 
  mutate(
    mod_1 = map(train, ~lm(formula = formula(mod_1), data = .x)),
    mod_2 = map(train, ~lm(formula = formula(mod_2), data = .x)),
    mod_3 = map(train, ~lm(formula = formula(mod_3), data = .x)),
    mod_4 = map(train, ~lm(formula = formula(mod_4), data = .x)),
    mod_5 = map(train, ~lm(formula = formula(mod_5), data = .x)),
    mod_6 = map(train, ~lm(formula = formula(mod_6), data = .x)),
    mod_7 = map(train, ~lm(formula = formula(mod_7), data = .x))
    ) %>% 
  mutate(
    rmse_1 = map2_dbl(mod_1, test, ~rmse(model = .x, data = .y)),
    rmse_2 = map2_dbl(mod_2, test, ~rmse(model = .x, data = .y)),
    rmse_3 = map2_dbl(mod_3, test, ~rmse(model = .x, data = .y)),
    rmse_4 = map2_dbl(mod_4, test, ~rmse(model = .x, data = .y)),
    rmse_5 = map2_dbl(mod_5, test, ~rmse(model = .x, data = .y)),
    rmse_6 = map2_dbl(mod_6, test, ~rmse(model = .x, data = .y)),
    rmse_7 = map2_dbl(mod_7, test, ~rmse(model = .x, data = .y))
    )
```


```{r}
cv_df %>% 
  pivot_longer(
    rmse_1:rmse_7,
    names_to = "model", 
    values_to = "rmse",
    names_prefix = "rmse_") %>% 
  mutate(model = fct_inorder(model),
         model = fct_recode(model, "Model 1" = "1",
                                   "Model 2" = "2",
                                   "Model 3" = "3",
                                   "Model 4" = "4",
                                   "Model 5" = "5",
                                   "Model 6" = "6",
                                   "Model 7" = "7")
         ) %>% 
  ggplot(aes(x = model, y = rmse, fill = model)) + 
  geom_violin() + 
  labs(x = "",
       y = "RMSE", 
       title = "Cross Validation") +
  scale_fill_brewer(type = 'seq', palette = 'Blues') +
  theme(legend.position = 'none',
        plot.title = element_text(hjust = 0.5))
```

## Results

```{r}
mod_1 %>% 
  broom::tidy() %>% 
  knitr::kable()
```

