---
title: "Project Report"
subtitle: "Life Expectancy"
output: 
  html_document:
    toc: true
    toc_float: true
---

## Project Motivation

We all know someone who is “obsessed” with astrology or another popular way to interpret one’s characters and predict the future. Palmistry is the practice of fortune-telling and evaluating aspects of a person’s life through the study of the palm. The association between the lifeline in palm reading and longevity resembles life expectancy, which reflects the quality of our health and physical vitality at a given time. Similarly, life expectancy is a statistical measure of the average number of years a person of a given age expects to live and the key for accessing population health. 

Unsurprisingly, life expectancy around the world has fallen dramatically. According to the 2020 death data from the US Centers for Disease Control and Prevention's National Center for Health Statistics, in 2020, Covid-19 resulted in an enormous drop in life expectancy and an increase in the death rate in the United States. Human life span may have a maximum “absolute limit”. Health professionals calculate life expectancy at birth to better understand a country’s health over time. When analyzing life span, many variables are diving into the rise and fall of an individual’s life span, such as socioeconomic, genetic, and environmental factors. In order to better understand the measure of life expectancy, we will investigate via statistical methods and explore the parameters affecting the life span of individuals and how life expectancy can be estimated with regression models. Through this project, we hope that useful information could be retrieved and effects on an individual’s life expectancy could be effectively communicated to the audience in the hope of raising awareness. 

<br>

### Related Work 

Following are resources that have inspired this project:

* "How does U.S. life expectancy compare to other countries?" from The Peterson-KFF. [(Link)](https://www.healthsystemtracker.org/chart-collection/u-s-life-expectancy-compare-countries/)

* "Will We Live Longer in the Future?" from Futures Platform. [(Link)](https://www.futuresplatform.com/blog/will-we-live-longer-future)

* "Pandemic Caused Steepest Decline In U.S. Life Expectancy Since World War II, CDC Report Shows" from Forbes. [(Link)](https://www.forbes.com/sites/siladityaray/2021/12/22/pandemic-caused-steepest-decline-in-us-life-expectancy-since-world-war-ii-cdc-report-shows/?sh=6d0a856c4365)

* "US life expectancy fell by more than a year during coronavirus pandemic, research suggests" from CNN. [(Link)](https://www.cnn.com/2021/06/24/health/us-life-expectancy-covid-19-pandemic-study-wellness/index.html)

<div align="center">
<iframe width="560" height="315" src="https://www.youtube.com/embed/_30TjaV4F3g" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div>

<br>

## Research Questions


<br>

## Data

### Data Sources
The primary dataset ([Life Expectancy (WHO)](https://www.kaggle.com/kumarajarshi/life-expectancy-who)) used in this project is a combined dataset from the the Global Health Observatory (GHO) data repository under World Health Organization (WHO) and United Nations website with the help of Deeksha Russell and Duan Wang.This data consists of immunization related factors, mortality factors, economical factors and social factors for all countries from 2000 to 2015. We also used the [country-to-continent dataset](https://www.kaggle.com/statchaitya/country-to-continent) and [World borders dataset](http://thematicmapping.org/downloads/world_borders.php) to supplement our analysis.

<br>

### Data Cleaning


### Variables of Interest

**Response Variable:**

* `le`: Life Expectancy in age

**Predictor Variables:**

* `continent`: Name of the continent in which the country is located
* `year` : 2000 to 2015
* `status`: Development status of the country (Developed or Developing)
* `adult_mort`: Adult mortality rates of both sexes (Probability of dying between 15 and 60 years old per 1000 population)
* `infantdeaths`: Number of infant deaths per 1000 population
* `Alcohol`: Alcohol consumption (15+) per capita (in litres of pure alcohol)
* `percent_exp`: Government expenditure on health as a percentage of gross domestic product per capita (%)
* `total_exp`: General government expenditure on health as a percentage of total government expenditure (%)
* `hepatitis_b`: Hepatitis B immunization coverage among 1-year-old (%)
* `measles`: Number of reported measles cases per 1000 population
* `bmi`: Average body mass index of entire population
* `under_five`: Number of deaths in children aged under 5 years old per 1000 population
* `polio`: Polio immunization coverage among 1-year-old(%)
* `diphtheria`: Diphtheria tetanus toxoid and pertussis immunization coverage among 1-year-old (%)
* `hiv_aids`: Number of deaths in children aged 0 to 4 years old due to HIV/AIDS per 1000 live births
* `gdp`: Gross domestic product per capita in USD
* `population`: Population of the country
* `thin_1_19`: Prevalence of thinness among children and adolescents aged 10 to 19 (%)
* `thin_5_9`: Prevalence of thinness among children and adolescents aged 5 to 9 (%)
* `HDI`: Human development index in terms of income composition of resources (index ranging from 0 to 1)
* `schooling`: Number of years of Schooling

<br>

## Analysis

<br>

## Key Findings


<br>

## Discussions


<br>

## Conclusion



<br>

## Contributors
* AnMei Chen 
* Lynn Chen

