<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Hypothesis Test</title>

<script src="site_libs/header-attrs-2.11/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/yeti.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script src="site_libs/navigation-1.1/codefolding.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>








<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.tab('show');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->
<style type="text/css">
.code-folding-btn { margin-bottom: 4px; }
</style>



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Home</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="report.html">Project Report</a>
</li>
<li>
  <a href="exploratory.html">Exploratory Analysis</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Regression Analysis
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="statistical.html">Statistical Analysis</a>
    </li>
    <li>
      <a href="regression.html">Modeling</a>
    </li>
  </ul>
</li>
<li>
  <a href="https://anmei18.shinyapps.io/interactive_map/">Interactive Map</a>
</li>
<li>
  <a href="https://github.com/lc1002/LifeExpectancy">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">

<div class="btn-group pull-right float-right">
<button type="button" class="btn btn-default btn-xs btn-secondary btn-sm dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>Code</span> <span class="caret"></span></button>
<ul class="dropdown-menu dropdown-menu-right" style="min-width: 50px;">
<li><a id="rmd-show-all-code" href="#">Show All Code</a></li>
<li><a id="rmd-hide-all-code" href="#">Hide All Code</a></li>
</ul>
</div>



<h1 class="title toc-ignore">Hypothesis Test</h1>

</div>


<style type="text/css">

h1.title {
  font-size: 50px;
  text-align: left;   
  font-family: Papyrus;
  font-weight: bold;
  font-variant: small-caps
}
</style>
<p><br></p>
<p>There are countless factors that affects country’s average life expectancy and how long an individual will be expected to live. In continuation of the exploratory analysis, we want to dive more into the dataset to further investigate the variables and possibly excavate some interesting findings that we don’t normally aware of.</p>
<br>
<hr>
<div id="development-status" class="section level3">
<h3><strong>Development Status</strong></h3>
<p>When exploring the Development status variable, the one-way analysis of variance (ANOVA) is used in order to have an understanding on how the two different groups (Developed and Developing) respond. And from the result we obtained, a conclusion was drawn that there is statistically significant differences between the means of Developed countries and Developing countries.</p>
<p>Subsequently, we want to see if the dataset provides envidence for Developed countries having greater mean life expectancy than the Developing countries.</p>
<center>
<span class="math inline">\(H_{0}: \mu_{Developed} = \mu_{Developing}\)</span><br />
<span class="math inline">\(H_{1}: \mu_{Developed} &gt; \mu_{Developing}\)</span>
</center>
<p><br></p>
<p>We will perform two-sample T-Test since the true variance of the populations is unknown. And also use F-test to test if the variances of the two populations are equal.</p>
<pre class="r"><code>var.test(Developed$Mean_LE, Developing$Mean_LE) %&gt;% 
  broom::tidy() %&gt;% 
  dplyr::select(c(4,5,8,9)) %&gt;% 
  knitr::kable(table.attr = &quot;style=&#39;width:30%;&#39;&quot;)</code></pre>
<table>
<thead>
<tr class="header">
<th align="right">statistic</th>
<th align="right">p.value</th>
<th align="left">method</th>
<th align="left">alternative</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">0.1401705</td>
<td align="right">0</td>
<td align="left">F test to compare two variances</td>
<td align="left">two.sided</td>
</tr>
</tbody>
</table>
<ul>
<li>We obtain a p-value of <span class="math inline">\(2.21e^{-8}\)</span> which is less than <span class="math inline">\(\alpha = 0.05\)</span>. Hence we reject the null hypothesis and conclude that the variance of two populations is not equal.</li>
</ul>
<pre class="r"><code>t.test(Developed$Mean_LE, Developing$Mean_LE, alternative = &quot;greater&quot;, var.equal = FALSE) %&gt;% 
  broom::tidy() %&gt;% 
  dplyr::select(c(4,5,6,9)) %&gt;% 
  knitr::kable(table.attr = &quot;style=&#39;width:30%;&#39;&quot;)</code></pre>
<table>
<thead>
<tr class="header">
<th align="right">statistic</th>
<th align="right">p.value</th>
<th align="right">parameter</th>
<th align="left">method</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">13.21463</td>
<td align="right">0</td>
<td align="right">130.4326</td>
<td align="left">Welch Two Sample t-test</td>
</tr>
</tbody>
</table>
<ul>
<li>At significance level of 0.05, we reject the <span class="math inline">\(H_{0}\)</span> since <span class="math inline">\(p-value &lt; 2.2e^{-16} &lt; \alpha = 0.05\)</span>. Thus, we conclude that the life expectancy for developed countries is greater than the developing countries.</li>
</ul>
<br>
<hr>
</div>
<div id="income-composition-of-resources-hdi" class="section level3">
<h3><strong>Income composition of resources (HDI)</strong></h3>
<p>The Human Development Index (HDI) is a statistic composite index of average achievement in key dimensions of human development: health (life expectancy), education (knowledge), and per capita income indicators (standard of living); it measures how good a country is at using its resources. By definition, life expectancy is one of the aspects of HDI measure, we want to see if there’s strong relationship between HDI and life expectancy; if countries that spend a higher proportion of their resources on human development would have a higher life expectancy.</p>
<pre class="r"><code>human_develop %&gt;% 
  ggplot(aes(x = mean_HDI, y = mean_LE)) +
  geom_point() +
  geom_smooth(method = &quot;lm&quot;) +
  stat_cor(aes(label = ..r.label..), method = &quot;pearson&quot;,  label.y = 75,color = &quot;red&quot;) +
  labs(title = &quot;Mean Life Expectancy VS. Mean HDI&quot;,
       x = &quot;Mean HDI&quot;,
       y = &quot;Mean Life Expectancy (Years)&quot;)</code></pre>
<p><img src="statistical_files/figure-html/unnamed-chunk-7-1.png" width="80%" /></p>
<ul>
<li>We obtain a correlation coefficient value of r = 0.79, which shows a significant positive correlation between life expectancy and HDI. This implies that countries with higher income composition of resources for human development and utilizes resources effectively are more likely to have higher life expectancy. Thus, countries could spend more on human development in order to achieve higher life expectancy.</li>
</ul>
<br>
<hr>
</div>
<div id="infant-deaths-and-under-five-deaths" class="section level3">
<h3><strong>Infant deaths and Under-five deaths</strong></h3>
<p>From the <a href="regression_files/figure-html/unnamed-chunk-3-1.png">correlation matrix</a>, the variable infant deaths and under-five deaths are highly correlated. Hence, we want to compare the proportions of the two variables (infant deaths and under-five deaths) using two-proportions z-test.</p>
<center>
<span class="math inline">\(H_{0}: p_{infant} = p_{under five}\)</span><br />
<span class="math inline">\(H_{1}: p_{infant} \ne p_{under five}\)</span>
</center>
<pre class="r"><code>prop.test(x, n, correct = FALSE) %&gt;% 
  broom::tidy() %&gt;% 
  dplyr::select(c(3,4,5,8)) %&gt;% 
  knitr::kable(digits = 4)</code></pre>
<table>
<colgroup>
<col width="10%" />
<col width="8%" />
<col width="10%" />
<col width="72%" />
</colgroup>
<thead>
<tr class="header">
<th align="right">statistic</th>
<th align="right">p.value</th>
<th align="right">parameter</th>
<th align="left">method</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">1.8747</td>
<td align="right">0.1709</td>
<td align="right">1</td>
<td align="left">2-sample test for equality of proportions without continuity correction</td>
</tr>
</tbody>
</table>
<ul>
<li><p>At 0.05 significance level, we have p-value = 0.1709 <span class="math inline">\(&gt; \alpha = 0.05\)</span>, thus, we fail to reject the null hypothesis and there is insufficient evidence to conclude that there is significant difference in the two independent proportions. Hence, we need to take into consideration of possible collinearity between the infant deaths variable and the under-five deaths variable when building the regression model.</p></li>
<li><p>We can see from the <a href="regression_files/figure-html/unnamed-chunk-3-1.png">correlation matrix</a> that the correlation coefficient between infant deaths and life expectancy is negative (r = -0.2), and similarly between under-five deaths and life expectancy (r = -0.22), which means that when infant deaths or under-five deaths increase, life expectancy will eventually decreases.</p></li>
</ul>
<br>
<hr>
</div>
<div id="alcohol" class="section level3">
<h3><strong>Alcohol</strong></h3>
<p>A recent cohort study showed that light-to-moderate alcohol intake is positively associated with longevity <a href="https://academic.oup.com/ageing/article/49/3/395/5730334">(Brandts et al., 2020)</a>. Another study conducted by a group of Harvard researchers on how lifestyle factors affect life expectancy showed evidence that people who take a few alcoholic drinks a week tends to live more years free of diabetes and heart disease than those who don’t drink or binge drink <a href="https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6207481/">(Li et al., 2018)</a>.</p>
<p>We want to see if life expectancy shows any strong correlation with drinking alcohol using our data.</p>
<pre class="r"><code>alc %&gt;% 
  ggplot(aes(x = mean_alc, y = mean_LE)) +
  geom_point() +
  geom_smooth(method = &quot;lm&quot;) +
  stat_cor(aes(label = ..r.label..), method = &quot;pearson&quot;, label.x = 10, label.y = 60, color = &quot;red&quot;) +
  labs(title = &quot;Mean Life Expectancy VS. Mean Alcohol Consumption&quot;,
       x = &quot;Alcohol Consumption (per capita (15+) consumption (in litres of pure alcohol))&quot;,
       y = &quot;Life Expectancy (Years)&quot;) </code></pre>
<p><img src="statistical_files/figure-html/unnamed-chunk-11-1.png" width="80%" /></p>
<ul>
<li>Surprisingly, in accordance with the studies, the scatter plot demonstrates that alcohol consumption has a positive correlation (r = 0.44) with life expectancy.</li>
</ul>
<pre class="r"><code>alc_mortality %&gt;% 
  ggplot(aes(x = mean_alc, y = mean_mortality)) +
  geom_point() +
  geom_smooth(method = &quot;lm&quot;) +
  stat_cor(method = &quot;pearson&quot;, label.x = 8, color = &quot;red&quot;) +
  labs(title = &quot;Mean Adult Mortality Rates VS. Mean Alcohol Consumption&quot;,
       x = &quot;Alcohol Consumption (per capita (15+) consumption (in litres of pure alcohol))&quot;,
       y = &quot;Adult Mortality Rates (per 1000 population)&quot;) </code></pre>
<p><img src="statistical_files/figure-html/unnamed-chunk-13-1.png" width="80%" /></p>
<ul>
<li>Although there’s no strong correlation between adult mortality rates and alcohol consumption, but having a p-value = 0.00083 we see that the correlation coefficient would still be significant. Even though, we can’t reach a strong conclusion regarding the correlation, interestingly, there’s evidence showing that alcohol consumption is positively associated (r = 0.44) with life expectancy and negatively associated (r = -0.24) with adult mortality.</li>
</ul>
<br>
<hr>
</div>
<div id="correlation-between-immunization-and-other-health-related-factors" class="section level3">
<h3><strong>Correlation between immunization and other health related factors</strong></h3>
<p>By understanding correlations between variables, we could gain knowledge on the factors that will affect life expectancy the most.</p>
<pre class="r"><code>cor_df =
  le_df %&gt;%
  dplyr::select(c(le, hepatitis_b, measles, polio, diphtheria, hiv_aids, thin_1_19, thin_5_9))

corrplot(cor(cor_df), type = &quot;upper&quot;, diag = FALSE, method = &quot;square&quot;, addCoef.col = &quot;black&quot;, number.cex = 1, tl.col = &quot;black&quot;, tl.cex = .8)</code></pre>
<p><img src="statistical_files/figure-html/unnamed-chunk-14-1.png" width="80%" /></p>
<ul>
<li><p>Life Expectancy has moderate negative correlation with HIV/AIDS, Thinness_1_19_years, and Thinness_5_9_years. And has low negative correlation with Measles.</p></li>
<li><p>Life Expectancy moderate positive correlation with Diphtheria, Polio and Hepatitis_B</p></li>
</ul>
<p><br></p>
<p>In the US, nearly all Americans have healthcare or health insurance, the accessibility to health care undoubtedly decreases mortality and increases life expectancy. A study conducted for East African countries have shown that there is a strong positive association between total healthcare expenditures and life expectancy; also, a negative relationship between healthcare expenditures and number of infant and under-five deaths <a href="https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5636241/">Bein et al., 2017</a>.</p>
<pre class="r"><code>toalexp %&gt;% 
  ggplot(aes(x = mean_toalexp, y = mean_LE)) +
  geom_point() +
  geom_smooth(method = &quot;lm&quot;) +
  stat_cor(method = &quot;pearson&quot;,label.y = 85, color = &quot;red&quot;) +
  stat_regline_equation(label.y = 82, aes(label = ..rr.label..), color = &quot;red&quot;) +
  labs(title = &quot;Mean Healthcare Expenditures VS. Mean Life Expectancy&quot;,
       x = &quot;Healthcare Expedicture (% of Total Expenditure)&quot;,
       y = &quot;Life Expectancy (Years)&quot;) </code></pre>
<p><img src="statistical_files/figure-html/unnamed-chunk-16-1.png" width="80%" /></p>
<pre class="r"><code>B = exp_inf %&gt;% 
  ggplot(aes(x = mean_toalexp, y = mean_inf)) +
  geom_point() +
  geom_smooth(method = &quot;lm&quot;) +
  stat_cor(aes(label = ..r.label..), method = &quot;pearson&quot;, color = &quot;red&quot;) +
  labs(title = &quot;Mean Healthcare Expenditures VS. Mean Infant Deaths&quot;,
       x = &quot;Healthcare Expedicture (% of Total Expenditure)&quot;,
       y = &quot;Infant Deaths&quot;) 

C = exp_underfive %&gt;% 
  ggplot(aes(x = mean_toalexp, y = mean_under)) +
  geom_point() +
  geom_smooth(method = &quot;lm&quot;) +
  stat_cor(aes(label = ..r.label..), method = &quot;pearson&quot;, color = &quot;red&quot;) +
  labs(title = &quot;Mean Healthcare Expenditures VS. Mean Under-five Deaths&quot;,
       x = &quot;Healthcare Expedicture (% of Total Expenditure)&quot;,
       y = &quot;Under-five Deaths&quot;) 

dev.off()</code></pre>
<pre><code>## null device 
##           1</code></pre>
<pre class="r"><code>gridExtra::grid.arrange(B, C, nrow = 1)</code></pre>
<ul>
<li>Our dataset also shows evidence that expenditure spend on health is positively associated (r = 0.22) with life expectancy and negatively associated with infant (r = -0.16) and under-five (r = -0.16) deaths.</li>
</ul>
<p>Now, it will be interesting to see if countries with low life expectancy (&lt;69 (mean)) spend less of their government expenditure on health and if those countries should increase their total expenditure on healthcare to increase life expectancy.</p>
<pre class="r"><code>health_Low = 
  le_df %&gt;% 
  filter(le &lt; 69) %&gt;% 
  group_by(country) %&gt;% 
  summarize(Mean_exp = mean(total_exp))

health_High = 
  le_df %&gt;% 
  filter(!le &lt; 69) %&gt;% 
  group_by(country) %&gt;% 
  summarize(Mean_exp = mean(total_exp))

t.test(health_Low$Mean_exp, health_High$Mean_exp) %&gt;% 
  broom::tidy() %&gt;% 
  dplyr::select(c(4,5,6,9)) %&gt;% 
  knitr::kable(table.attr = &quot;style=&#39;width:30%;&#39;&quot;)</code></pre>
<table>
<thead>
<tr class="header">
<th align="right">statistic</th>
<th align="right">p.value</th>
<th align="right">parameter</th>
<th align="left">method</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">-2.001813</td>
<td align="right">0.0469262</td>
<td align="right">166.754</td>
<td align="left">Welch Two Sample t-test</td>
</tr>
</tbody>
</table>
<ul>
<li><p>The p-value we get from the t-test is 0.047 which is less than significance level of 0.05, thus, we will reject the null hypothesis and conclude that countries with high life expectancy spend higher proportion of their government expenditure on healthcare than countries with low life expectancy.</p></li>
<li><p>Also, from the plot above, we see that total expenditure on health as a percentage of of total government expenditure is a factor contribute in predicting life expectancy since we have a p-value = 0.0025. However, we can infer that solely total healthcare expenditure factor will not accurately predict life expectancy since we obtain a pretty low <span class="math inline">\(R^{2}\)</span> value of 0.047. Therefore, we want to look at other factors along with total expenditures and see how they are going to affect the life expectancy.</p></li>
</ul>
<br>
<hr>
</div>
<div id="correlation-between-socioeconomic-and-behavioral-factors" class="section level3">
<h3><strong>Correlation between socioeconomic and behavioral factors</strong></h3>
<p>Many demographic, socioeconomic, and behavioral factors can be linked with individual’s life expectancy. In the United States, higher income was associated with longer life expectancy, and there are increasing differences in life expectancy across income groups <a href="https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4866586/">Chetty et al., 2016</a>. We will conduct linear regression analysis based on SES and behavioral factors such as <code>alcohol</code>, <code>percent_exp</code>, <code>total_exp</code>, <code>bmi</code>, <code>population</code>, <code>HDI</code>, <code>schooling</code>, and <code>GDP</code> to have a deeper understanding on how these factors influence life expectancy of a country.</p>
<pre class="r"><code>SES = lm(le ~ alcohol + percent_exp + total_exp + bmi + population + HDI + schooling, data = le_df)
vif1 = check_collinearity(SES)

summary(SES)</code></pre>
<pre><code>## 
## Call:
## lm(formula = le ~ alcohol + percent_exp + total_exp + bmi + population + 
##     HDI + schooling, data = le_df)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -27.9509  -2.6411   0.3347   3.1516  28.8618 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  4.551e+01  4.255e-01 106.960  &lt; 2e-16 ***
## alcohol     -8.057e-02  3.138e-02  -2.567   0.0103 *  
## percent_exp  4.681e-04  5.789e-05   8.086  8.9e-16 ***
## total_exp    3.668e-02  4.442e-02   0.826   0.4090    
## bmi          9.355e-02  6.324e-03  14.793  &lt; 2e-16 ***
## population   7.669e-10  1.916e-09   0.400   0.6890    
## HDI          1.293e+01  8.436e-01  15.329  &lt; 2e-16 ***
## schooling    1.005e+00  5.493e-02  18.290  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 5.674 on 2930 degrees of freedom
## Multiple R-squared:  0.6454, Adjusted R-squared:  0.6445 
## F-statistic: 761.7 on 7 and 2930 DF,  p-value: &lt; 2.2e-16</code></pre>
<ul>
<li>We see that <code>total_exp</code> and <code>population</code> are both insignificant.</li>
</ul>
<pre class="r"><code>add_GDP = lm(le ~ alcohol + percent_exp + total_exp + bmi + population + HDI + schooling + gdp, data = le_df)
vif2 = check_collinearity(add_GDP) 
summary(add_GDP)</code></pre>
<pre><code>## 
## Call:
## lm(formula = le ~ alcohol + percent_exp + total_exp + bmi + population + 
##     HDI + schooling + gdp, data = le_df)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -27.9211  -2.5875   0.3405   3.2346  28.5543 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  4.563e+01  4.246e-01 107.460  &lt; 2e-16 ***
## alcohol     -8.292e-02  3.127e-02  -2.652  0.00805 ** 
## percent_exp -1.346e-05  1.158e-04  -0.116  0.90748    
## total_exp    6.439e-02  4.463e-02   1.443  0.14921    
## bmi          9.108e-02  6.322e-03  14.407  &lt; 2e-16 ***
## population   9.898e-10  1.909e-09   0.518  0.60417    
## HDI          1.240e+01  8.477e-01  14.630  &lt; 2e-16 ***
## schooling    9.976e-01  5.475e-02  18.222  &lt; 2e-16 ***
## gdp          8.529e-05  1.779e-05   4.795 1.71e-06 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 5.653 on 2929 degrees of freedom
## Multiple R-squared:  0.6481, Adjusted R-squared:  0.6472 
## F-statistic: 674.4 on 8 and 2929 DF,  p-value: &lt; 2.2e-16</code></pre>
<ul>
<li>Surprisingly, <code>percent_exp</code> becomes insignificant along with <code>total_exp</code> and <code>population</code> variables when <code>gdp</code> is added to the regression model. There’s possibility that some of the variables are strongly correlated (<code>percent_exp</code> and <code>gdp</code>).</li>
</ul>
<pre class="r"><code>ses_beh_df =
  le_df %&gt;%
  dplyr::select(c(le, alcohol, percent_exp, total_exp, bmi,gdp, HDI, population, schooling))

corrplot(cor(ses_beh_df), type = &quot;upper&quot;, diag = FALSE, method = &quot;square&quot;, addCoef.col = &quot;black&quot;, number.cex = 0.5, tl.col = &quot;black&quot;, tl.cex = .8)</code></pre>
<p><img src="statistical_files/figure-html/unnamed-chunk-20-1.png" width="80%" /></p>
<ul>
<li><code>percent_exp</code> and <code>gdp</code> are strongly correlated as well, which explains why <code>percent_exp</code> becomes insignificant when <code>gdp</code> factor was added to the model.</li>
</ul>
<pre class="r"><code>interact_term = lm(le ~ alcohol + percent_exp + total_exp + bmi + HDI + schooling + gdp + percent_exp*gdp, data = le_df)
vif2 = check_collinearity(interact_term) 

summary(interact_term)</code></pre>
<pre><code>## 
## Call:
## lm(formula = le ~ alcohol + percent_exp + total_exp + bmi + HDI + 
##     schooling + gdp + percent_exp * gdp, data = le_df)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -27.8509  -2.6499   0.3338   3.2502  28.3700 
## 
## Coefficients:
##                   Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)      4.587e+01  4.254e-01 107.834  &lt; 2e-16 ***
## alcohol         -9.224e-02  3.129e-02  -2.948 0.003228 ** 
## percent_exp      4.649e-04  1.720e-04   2.704 0.006899 ** 
## total_exp        6.385e-02  4.447e-02   1.436 0.151181    
## bmi              9.020e-02  6.302e-03  14.312  &lt; 2e-16 ***
## HDI              1.235e+01  8.455e-01  14.607  &lt; 2e-16 ***
## schooling        9.741e-01  5.496e-02  17.726  &lt; 2e-16 ***
## gdp              8.857e-05  1.777e-05   4.985 6.54e-07 ***
## percent_exp:gdp -7.580e-09  2.023e-09  -3.747 0.000182 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 5.64 on 2929 degrees of freedom
## Multiple R-squared:  0.6498, Adjusted R-squared:  0.6488 
## F-statistic: 679.2 on 8 and 2929 DF,  p-value: &lt; 2.2e-16</code></pre>
<ul>
<li>When the interaction term of <code>percent_exp</code> and <code>gdp</code> was included in the model, <code>percent_exp</code> once again becomes significant. We see that the interaction term is statistically significant at significance level of 0.001. Also, the adjusted R-squared has increased to 0.6488. Thus, the interaction term is probably important.</li>
</ul>
<p>Income composition of resources (<code>HDI</code>) is highly correlated with <code>life expectancy</code> and <code>schooling</code>, it shows evidence that it’s a composite variable.</p>
<pre class="r"><code>remove_HDI = lm(le ~ alcohol + percent_exp + total_exp + bmi + population + schooling + gdp, data = le_df)
vif3 = check_collinearity(remove_HDI) ## all vif drop below 2

summary(remove_HDI)</code></pre>
<pre><code>## 
## Call:
## lm(formula = le ~ alcohol + percent_exp + total_exp + bmi + population + 
##     schooling + gdp, data = le_df)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -27.8034  -2.8216   0.5287   3.5853  27.8350 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  4.631e+01  4.371e-01 105.957  &lt; 2e-16 ***
## alcohol     -6.901e-02  3.237e-02  -2.132   0.0331 *  
## percent_exp -1.093e-04  1.198e-04  -0.913   0.3615    
## total_exp    2.553e-02  4.614e-02   0.553   0.5802    
## bmi          1.021e-01  6.501e-03  15.708  &lt; 2e-16 ***
## population   1.824e-09  1.976e-09   0.923   0.3560    
## schooling    1.553e+00  4.085e-02  38.019  &lt; 2e-16 ***
## gdp          1.192e-04  1.827e-05   6.526 7.94e-11 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 5.855 on 2930 degrees of freedom
## Multiple R-squared:  0.6224, Adjusted R-squared:  0.6215 
## F-statistic: 689.9 on 7 and 2930 DF,  p-value: &lt; 2.2e-16</code></pre>
<ul>
<li>Checking for collinearity and VIF all fell below 2, HDI could be a combination of other variables.</li>
</ul>
<br>
<hr>
<p>We also want to take a deeper looking at schooling factor, since education brings awareness about healthy living and it shows that it’s a statistically significance factor from above regression analysis. In addition, study shown that adults with at least a Master’s degree brings about a life expectancy of 14.7 years more than people who had not finished high school, and 8.3 years more than people who had completed high school <a href="https://mchandaids.org/index.php/IJMA/article/view/402">(Singh &amp; Lee, 2021)</a>. We want to use the t-test for our data to see if average number of years in school has a significant impact on life expectancy. We will categorized <code>schooling</code> variable into Low (schooling <span class="math inline">\(\le 12\)</span>) and High (schooling <span class="math inline">\(&gt; 12\)</span>)</p>
<center>
<span class="math inline">\(H_{0}: \mu_{Low} = \mu_{High}\)</span><br />
<span class="math inline">\(H_{1}: \mu_{Low} &lt; \mu_{High}\)</span>
</center>
<p><br></p>
<pre class="r"><code>var.test(school_low$mean_le, school_high$mean_le) %&gt;% 
  broom::tidy() %&gt;% 
  dplyr::select(c(4,5,8,9)) %&gt;% 
  knitr::kable(table.attr = &quot;style=&#39;width:30%;&#39;&quot;)</code></pre>
<table>
<thead>
<tr class="header">
<th align="right">statistic</th>
<th align="right">p.value</th>
<th align="left">method</th>
<th align="left">alternative</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">2.744049</td>
<td align="right">1e-07</td>
<td align="left">F test to compare two variances</td>
<td align="left">two.sided</td>
</tr>
</tbody>
</table>
<ul>
<li>We obtain a p-value of <span class="math inline">\(1e^{-7}\)</span> which is less than <span class="math inline">\(\alpha = 0.05\)</span>. Hence we reject the null hypothesis and conclude that the variance of two populations is not equal.</li>
</ul>
<pre class="r"><code>t.test(school_low$mean_le, school_high$mean_le, alternative = &quot;less&quot;, var.equal = FALSE) %&gt;%
  broom::tidy() %&gt;% 
  dplyr::select(c(4,5,6,9)) %&gt;% 
  knitr::kable(table.attr = &quot;style=&#39;width:30%;&#39;&quot;)</code></pre>
<table>
<thead>
<tr class="header">
<th align="right">statistic</th>
<th align="right">p.value</th>
<th align="right">parameter</th>
<th align="left">method</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">-11.87915</td>
<td align="right">0</td>
<td align="right">183.5663</td>
<td align="left">Welch Two Sample t-test</td>
</tr>
</tbody>
</table>
<ul>
<li>At significance level of 0.05, we reject the <span class="math inline">\(H_{0}\)</span> since <span class="math inline">\(p-value &lt; 2.2e^{-16} \approx 0 &lt; \alpha = 0.05\)</span>. Thus, we conclude that the life expectancy for people with higher number of years of schooling is higher than the life expectancy of people with lower number of years of schooling. Thus, we schooling is a significant factor in predicting life expectancy.</li>
</ul>
<br>
<hr>
<center>
<p><font size="2"> Contributors: AnMei Chen and Lynn Chen.</font><br> <font size="2">The Github repository for this website can be found <a href="https://github.com/lc1002/LifeExpectancy">here</a>, and the corresponding Github repository for this project is located <a href="https://github.com/lc1002/LifeExpectancyAnalysis">here</a>. </font></p>
<img src="image/mailman.png" alt="logo" style="width:30%; height:20%; ">
</center>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->
<script>
$(document).ready(function () {
  window.initializeCodeFolding("hide" === "show");
});
</script>

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
